#!/usr/bin/env bash
# Write gitignored prototypes/dc-dashboard/tripwire-dashboard.config.js from .env.
#
# Preferred (direct browser → Supabase):
#   SUPABASE_URL + SUPABASE_ANON_KEY
#
# If anon key is missing but SUPABASE_SERVICE_ROLE_KEY exists, use the local
# Live proxy instead (keeps service_role off the browser):
#   node scripts/serve-dashboard.mjs
#
# Usage (from repo root):
#   ./scripts/sync-dashboard-config.sh

set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
ENV_FILE="${ROOT}/.env"
OUT="${ROOT}/prototypes/dc-dashboard/tripwire-dashboard.config.js"

if [[ ! -f "$ENV_FILE" ]]; then
  echo "error: missing ${ENV_FILE} — copy .env.example and fill Supabase keys." >&2
  exit 1
fi

SUPABASE_URL="$(grep -E '^SUPABASE_URL=' "$ENV_FILE" | tail -n1 | cut -d= -f2- | tr -d '"' | tr -d "'")"
SUPABASE_ANON_KEY="$(grep -E '^SUPABASE_ANON_KEY=' "$ENV_FILE" | tail -n1 | cut -d= -f2- | tr -d '"' | tr -d "'" || true)"
SUPABASE_SERVICE_ROLE_KEY="$(grep -E '^SUPABASE_SERVICE_ROLE_KEY=' "$ENV_FILE" | tail -n1 | cut -d= -f2- | tr -d '"' | tr -d "'" || true)"

if [[ -z "${SUPABASE_URL}" ]]; then
  echo "error: SUPABASE_URL is empty in .env" >&2
  exit 1
fi

if [[ -z "${SUPABASE_ANON_KEY}" ]]; then
  cat >&2 <<EOF
error: SUPABASE_ANON_KEY is empty in .env — cannot write a direct browser config.

Why the chip says "Missing API key" / Live shows not configured:
  tripwire-dashboard.config.js has SUPABASE_URL but an empty anon key, so
  tripwire-live.js refuses to call Supabase and returns source "mock".

Fix (pick one):

  A) Local Live proxy (works with your existing SERVICE_ROLE key; recommended now):
       node scripts/serve-dashboard.mjs
       # open http://127.0.0.1:8765/Tripwire.dc.html → Live (Supabase)

  B) Direct browser → Supabase (anon/public key):
       1. Supabase → Project Settings → API → copy anon / public key
       2. Set SUPABASE_ANON_KEY=... in .env
       3. Re-run: ./scripts/sync-dashboard-config.sh
       4. cd prototypes/dc-dashboard && python3 -m http.server 8765

service_role present in .env: $([[ -n "${SUPABASE_SERVICE_ROLE_KEY}" ]] && echo yes || echo no)
EOF
  exit 1
fi

js_escape() {
  printf '%s' "$1" | sed 's/\\/\\\\/g; s/"/\\"/g'
}

URL_ESC="$(js_escape "$SUPABASE_URL")"
KEY_ESC="$(js_escape "$SUPABASE_ANON_KEY")"

cat >"$OUT" <<EOF
// Auto-generated by scripts/sync-dashboard-config.sh — gitignored, do NOT commit.
// The anon key is safe for browser use — it only grants access through RLS policies.
window.__TRIPWIRE_CONFIG = {
  SUPABASE_URL: "${URL_ESC}",
  SUPABASE_ANON_KEY: "${KEY_ESC}",
};
EOF

echo "Wrote ${OUT#"${ROOT}"/} (URL len=${#SUPABASE_URL}, anon key len=${#SUPABASE_ANON_KEY})."
echo "Serve: cd prototypes/dc-dashboard && python3 -m http.server 8765"
echo "Open:  http://127.0.0.1:8765/Tripwire.dc.html  → Live (Supabase)"
