#!/usr/bin/env bash
# Wait for OAuth env vars, write gitignored local pizauth config, reload daemon.
# Usage:
#   cd labs/external-tools-sandbox
#   # put PIZAUTH_PROVIDER + PIZAUTH_CLIENT_ID (+ SECRET) in .env
#   ./pizauth/scripts/oauth-setup.sh
#
# Never prints secret values. Exit 2 = BLOCKED-HITL (missing credentials).
set -euo pipefail

DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
ROOT="$(cd "$DIR/.." && pwd)"
cd "$ROOT"

# Load lab .env if present (does not override already-exported vars).
if [[ -f "$ROOT/.env" ]]; then
  set -a
  # shellcheck disable=SC1091
  source "$ROOT/.env"
  set +a
fi

PROVIDER="${PIZAUTH_PROVIDER:-}"
CLIENT_ID="${PIZAUTH_CLIENT_ID:-}"
CLIENT_SECRET="${PIZAUTH_CLIENT_SECRET:-}"
ACCOUNT_EMAIL="${PIZAUTH_ACCOUNT_EMAIL:-lab@example.com}"
ACCOUNT_NAME="${PIZAUTH_ACCOUNT_NAME:-lab}"
HTTP_LISTEN="${PIZAUTH_HTTP_LISTEN:-0.0.0.0:14204}"
# Redirect URI registered at the IdP — must match what pizauth sends.
REDIRECT_URI="${PIZAUTH_REDIRECT_URI:-http://localhost:14204/}"
WAIT_SECS="${PIZAUTH_OAUTH_WAIT_SECS:-0}"
LOCAL_CONF="$DIR/config/pizauth.local.conf"
COMPOSE_CONF_PATH="/config/pizauth.local.conf"

redact_note() {
  echo "[oauth-setup] $*"
}

check_required() {
  local missing=0
  if [[ -z "$PROVIDER" ]]; then
    redact_note "missing PIZAUTH_PROVIDER (google|microsoft)"
    missing=1
  fi
  if [[ -z "$CLIENT_ID" ]]; then
    redact_note "missing PIZAUTH_CLIENT_ID"
    missing=1
  fi
  if [[ -z "$CLIENT_SECRET" ]]; then
    redact_note "PIZAUTH_CLIENT_SECRET empty (OK only if IdP allows public client)"
  fi
  return "$missing"
}

wait_for_env() {
  if ! [[ "$WAIT_SECS" =~ ^[0-9]+$ ]] || (( WAIT_SECS <= 0 )); then
    return 1
  fi
  redact_note "waiting up to ${WAIT_SECS}s for env vars (poll every 5s)…"
  local end=$((SECONDS + WAIT_SECS))
  while (( SECONDS < end )); do
    if [[ -f "$ROOT/.env" ]]; then
      set -a
      # shellcheck disable=SC1091
      source "$ROOT/.env"
      set +a
      PROVIDER="${PIZAUTH_PROVIDER:-}"
      CLIENT_ID="${PIZAUTH_CLIENT_ID:-}"
      CLIENT_SECRET="${PIZAUTH_CLIENT_SECRET:-}"
      ACCOUNT_EMAIL="${PIZAUTH_ACCOUNT_EMAIL:-$ACCOUNT_EMAIL}"
    fi
    if [[ -n "$PROVIDER" && -n "$CLIENT_ID" ]]; then
      return 0
    fi
    sleep 5
  done
  return 1
}

if ! check_required; then
  wait_for_env || true
fi

if ! check_required; then
  redact_note "BLOCKED-HITL: fill labs/external-tools-sandbox/.env (see .env.example + QUESTIONS.md)"
  redact_note "Register redirect URI exactly: ${REDIRECT_URI}"
  exit 2
fi

case "$PROVIDER" in
  google|gmail)
    AUTH_URI="https://accounts.google.com/o/oauth2/auth"
    TOKEN_URI="https://oauth2.googleapis.com/token"
    SCOPES_BLOCK='scopes = ["https://mail.google.com/"];'
    ;;
  microsoft|ms|office365|entra)
    AUTH_URI="https://login.microsoftonline.com/common/oauth2/v2.0/authorize"
    TOKEN_URI="https://login.microsoftonline.com/common/oauth2/v2.0/token"
    SCOPES_BLOCK='scopes = [
        "https://outlook.office365.com/IMAP.AccessAsUser.All",
        "https://outlook.office365.com/SMTP.Send",
        "offline_access"
    ];'
    ;;
  *)
    redact_note "unknown PIZAUTH_PROVIDER='$PROVIDER' (use google|microsoft)"
    exit 2
    ;;
esac

esc() {
  printf '%s' "$1" | sed -e 's/\\/\\\\/g' -e 's/"/\\"/g'
}

SECRET_LINE=""
if [[ -n "$CLIENT_SECRET" ]]; then
  SECRET_LINE="    client_secret = \"$(esc "$CLIENT_SECRET")\";"
fi

umask 077
cat >"$LOCAL_CONF" <<EOF
// Generated by scripts/oauth-setup.sh — DO NOT COMMIT (gitignored).
// Redirect URI to register at IdP: ${REDIRECT_URI}
http_listen = "${HTTP_LISTEN}";
https_listen = none;

auth_notify_cmd = "echo \"[pizauth] auth needed for \$PIZAUTH_ACCOUNT: \$PIZAUTH_URL\" >&2";
error_notify_cmd = "echo \"[pizauth] error for \$PIZAUTH_ACCOUNT: \$PIZAUTH_MSG\" >&2";

account "$(esc "$ACCOUNT_NAME")" {
    auth_uri = "${AUTH_URI}";
    token_uri = "${TOKEN_URI}";
    client_id = "$(esc "$CLIENT_ID")";
${SECRET_LINE}
    ${SCOPES_BLOCK}
    auth_uri_fields = { "login_hint": "$(esc "$ACCOUNT_EMAIL")" };
}
EOF

redact_note "wrote gitignored config: config/pizauth.local.conf"
redact_note "provider=${PROVIDER} account=${ACCOUNT_NAME} client_id_len=${#CLIENT_ID} secret_set=$([[ -n $CLIENT_SECRET ]] && echo yes || echo no)"
redact_note "register redirect URI: ${REDIRECT_URI}"

export PIZAUTH_CONFIG_PATH="$COMPOSE_CONF_PATH"

if ! command -v docker >/dev/null 2>&1; then
  redact_note "docker not available — config written; start daemon manually with -c ${COMPOSE_CONF_PATH}"
  exit 0
fi

CID="$(docker compose --profile pizauth ps -q pizauth 2>/dev/null || true)"
if [[ -z "$CID" ]]; then
  redact_note "starting pizauth with local conf…"
  PIZAUTH_CONFIG_PATH="$COMPOSE_CONF_PATH" docker compose --profile pizauth up -d --build
else
  redact_note "recreating pizauth so it picks up pizauth.local.conf…"
  PIZAUTH_CONFIG_PATH="$COMPOSE_CONF_PATH" docker compose --profile pizauth up -d --force-recreate pizauth
fi
CID="$(docker compose --profile pizauth ps -q pizauth)"

for _ in $(seq 1 30); do
  if docker exec "$CID" pizauth info -j -c "$COMPOSE_CONF_PATH" 2>/dev/null \
    | grep -q '"server_running":true'; then
    break
  fi
  sleep 1
done

redact_note "info:"
docker exec "$CID" pizauth info -j -c "$COMPOSE_CONF_PATH" 2>/dev/null || true
redact_note "status:"
docker exec "$CID" pizauth status 2>/dev/null || true

redact_note "requesting auth URL (show) — open in browser; client_id/secret redacted below"
set +e
SHOW_OUT="$(docker exec "$CID" pizauth show "$ACCOUNT_NAME" 2>&1)"
SHOW_RC=$?
set -e
printf '%s\n' "$SHOW_OUT" \
  | sed -E 's/(client_id|client_secret)=[^&[:space:]]+/\1=REDACTED/g'

if [[ "$SHOW_RC" -eq 0 ]]; then
  redact_note "OAuth LIVE: token already available for account=${ACCOUNT_NAME}"
  exit 0
fi

redact_note "PARTIAL: complete browser login at the URL above, then re-check:"
redact_note "  docker exec ${CID:0:12}… pizauth status"
redact_note "  docker exec … pizauth show ${ACCOUNT_NAME}"
exit 0
